import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/Navbar";
import { Toaster } from "@/components/ui/toaster";
import { LoaderProvider } from "@/context/LoaderContext";
import Loader from "./components/Loader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={inter.className}>
                <LoaderProvider>
                    <main>
                        <Navbar />
                        {children}
                    </main>
                    <Toaster />

                    <Loader />
                </LoaderProvider>
            </body>
        </html>
    );
}
